Fix the `SideBarRight` and other improvements
Frelya/react-site-editor pull request #115
Opened 2023-07-02 01:33 UTC by YacineSteeve

2023-07-02 01:33 UTC, YacineSteeve commented
Current dependencies on/for this PR:
* main
  * **PR #115** <a href="https://app.graphite.dev/github/pr/Frelya/react-site-editor/115" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/Frelya/react-site-editor/115?utm_source=stack-comment).

2023-07-03 10:31 UTC, epoundor requested changes

2023-07-03 10:31 UTC, epoundor commented on apps/frontend/src/components/Common/ContextMenu/index.ts
Why

2023-07-03 10:34 UTC, YacineSteeve commented on apps/frontend/src/utils/remove-non-serializable.ts
You're a little genius

2023-07-03 10:36 UTC, YacineSteeve commented on apps/frontend/src/components/Common/index.ts
These is for gathering components that won't be used in a single feature unit, but across all the app.
For example here the ContextMenu could be added in any place in the app. So can Buttons.

2023-07-03 10:40 UTC, YacineSteeve commented on apps/frontend/src/components/Common/ContextMenu/index.ts
To shorten `ContextMenu/ContextMenu`, and to improve isolation.

As you can see, I created many other index files like that. The purpose of this is to export from each folder ONLY the component that is meant to be used outside of it.

Some examples:

* In the `ContextMenu` folder, it is only the final `ContextMenu` component that would be used somewhere else. The `ContextMenuItem` don't have to.

* In the SideBar folder, only `SideBarLeft` and `SideBarRight` should be exported. The other components are units used to build those two.

2023-07-03 11:01 UTC, epoundor commented on apps/frontend/src/components/Common/index.ts
Yes I understand the idea.
But I prefer Atomic approach

2023-07-03 11:01 UTC, epoundor commented on apps/frontend/src/utils/remove-non-serializable.ts
Come on
I gonna "rougir"

2023-07-03 11:02 UTC, YacineSteeve commented on apps/frontend/src/components/Common/index.ts
Let me check about it

2023-07-06 08:21 UTC, epoundor approved these changes

2023-07-06 17:18 UTC, merged